### ISSUE TITLE
Create igniteui-react-quickstart application

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-react-wrappers#85]
Need to have a quickstart application based on ReactJS similar to our [AngularJS ](https://github.com/IgniteUI/igniteui-angular-seed) one for our tools usage.

Actions to implement:
- Fork the react app at https://github.com/facebookincubator/create-react-app
- Update its views to have the Grid(1), Combo and Editors controls as in the AngularJS
- Add a Dashboard view copying the configuration on our react io page demo - https://igniteui.github.io/igniteui-react/samples/dashboard/FinancialState.html
- Update documentation and tests in the Ignite UI context
- Publish the igniteui-react-quickstart app repo under IgniteUI.

**Comment by mpavlinov** [comment]
Closing this one as it is old. Currently we don't have plans for React quickstart application.
